/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminMainRouteImport } from './routes/admin/main'
import { Route as AdminInfluenciadoresRouteImport } from './routes/admin/influenciadores'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMainRoute = AdminMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfluenciadoresRoute = AdminInfluenciadoresRouteImport.update({
  id: '/influenciadores',
  path: '/influenciadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/main': typeof AdminMainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/main': typeof AdminMainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/main': typeof AdminMainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/influenciadores'
    | '/admin/main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/influenciadores'
    | '/admin/main'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/influenciadores'
    | '/admin/main'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/main': {
      id: '/admin/main'
      path: '/main'
      fullPath: '/admin/main'
      preLoaderRoute: typeof AdminMainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influenciadores': {
      id: '/admin/influenciadores'
      path: '/influenciadores'
      fullPath: '/admin/influenciadores'
      preLoaderRoute: typeof AdminInfluenciadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminInfluenciadoresRoute: typeof AdminInfluenciadoresRoute
  AdminMainRoute: typeof AdminMainRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminInfluenciadoresRoute: AdminInfluenciadoresRoute,
  AdminMainRoute: AdminMainRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
