/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminProdutoslistRouteImport } from './routes/admin/produtoslist'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminMainRouteImport } from './routes/admin/main'
import { Route as AdminInfluenciadoreslistRouteImport } from './routes/admin/influenciadoreslist'
import { Route as AdminInfluenciadoresRouteImport } from './routes/admin/influenciadores'
import { Route as AdminClienteslistRouteImport } from './routes/admin/clienteslist'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutoslistRoute = AdminProdutoslistRouteImport.update({
  id: '/produtoslist',
  path: '/produtoslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMainRoute = AdminMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInfluenciadoreslistRoute =
  AdminInfluenciadoreslistRouteImport.update({
    id: '/influenciadoreslist',
    path: '/influenciadoreslist',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInfluenciadoresRoute = AdminInfluenciadoresRouteImport.update({
  id: '/influenciadores',
  path: '/influenciadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClienteslistRoute = AdminClienteslistRouteImport.update({
  id: '/clienteslist',
  path: '/clienteslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clienteslist': typeof AdminClienteslistRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/influenciadoreslist': typeof AdminInfluenciadoreslistRoute
  '/admin/main': typeof AdminMainRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/produtoslist': typeof AdminProdutoslistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clienteslist': typeof AdminClienteslistRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/influenciadoreslist': typeof AdminInfluenciadoreslistRoute
  '/admin/main': typeof AdminMainRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/produtoslist': typeof AdminProdutoslistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clienteslist': typeof AdminClienteslistRoute
  '/admin/influenciadores': typeof AdminInfluenciadoresRoute
  '/admin/influenciadoreslist': typeof AdminInfluenciadoreslistRoute
  '/admin/main': typeof AdminMainRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/produtoslist': typeof AdminProdutoslistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clienteslist'
    | '/admin/influenciadores'
    | '/admin/influenciadoreslist'
    | '/admin/main'
    | '/admin/produtos'
    | '/admin/produtoslist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clienteslist'
    | '/admin/influenciadores'
    | '/admin/influenciadoreslist'
    | '/admin/main'
    | '/admin/produtos'
    | '/admin/produtoslist'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clienteslist'
    | '/admin/influenciadores'
    | '/admin/influenciadoreslist'
    | '/admin/main'
    | '/admin/produtos'
    | '/admin/produtoslist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtoslist': {
      id: '/admin/produtoslist'
      path: '/produtoslist'
      fullPath: '/admin/produtoslist'
      preLoaderRoute: typeof AdminProdutoslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/main': {
      id: '/admin/main'
      path: '/main'
      fullPath: '/admin/main'
      preLoaderRoute: typeof AdminMainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influenciadoreslist': {
      id: '/admin/influenciadoreslist'
      path: '/influenciadoreslist'
      fullPath: '/admin/influenciadoreslist'
      preLoaderRoute: typeof AdminInfluenciadoreslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/influenciadores': {
      id: '/admin/influenciadores'
      path: '/influenciadores'
      fullPath: '/admin/influenciadores'
      preLoaderRoute: typeof AdminInfluenciadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clienteslist': {
      id: '/admin/clienteslist'
      path: '/clienteslist'
      fullPath: '/admin/clienteslist'
      preLoaderRoute: typeof AdminClienteslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminClienteslistRoute: typeof AdminClienteslistRoute
  AdminInfluenciadoresRoute: typeof AdminInfluenciadoresRoute
  AdminInfluenciadoreslistRoute: typeof AdminInfluenciadoreslistRoute
  AdminMainRoute: typeof AdminMainRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminProdutoslistRoute: typeof AdminProdutoslistRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminClienteslistRoute: AdminClienteslistRoute,
  AdminInfluenciadoresRoute: AdminInfluenciadoresRoute,
  AdminInfluenciadoreslistRoute: AdminInfluenciadoreslistRoute,
  AdminMainRoute: AdminMainRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminProdutoslistRoute: AdminProdutoslistRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
