/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVendedoreslistRouteImport } from './routes/admin/vendedoreslist'
import { Route as AdminVendedoresRouteImport } from './routes/admin/vendedores'
import { Route as AdminTituloslistRouteImport } from './routes/admin/tituloslist'
import { Route as AdminTitulosRouteImport } from './routes/admin/titulos'
import { Route as AdminProdutoslistRouteImport } from './routes/admin/produtoslist'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminPedidoslistRouteImport } from './routes/admin/pedidoslist'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminMainRouteImport } from './routes/admin/main'
import { Route as AdminClienteslistRouteImport } from './routes/admin/clienteslist'
import { Route as AdminClientesRouteImport } from './routes/admin/clientes'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendedoreslistRoute = AdminVendedoreslistRouteImport.update({
  id: '/vendedoreslist',
  path: '/vendedoreslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendedoresRoute = AdminVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTituloslistRoute = AdminTituloslistRouteImport.update({
  id: '/tituloslist',
  path: '/tituloslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTitulosRoute = AdminTitulosRouteImport.update({
  id: '/titulos',
  path: '/titulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutoslistRoute = AdminProdutoslistRouteImport.update({
  id: '/produtoslist',
  path: '/produtoslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidoslistRoute = AdminPedidoslistRouteImport.update({
  id: '/pedidoslist',
  path: '/pedidoslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMainRoute = AdminMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClienteslistRoute = AdminClienteslistRouteImport.update({
  id: '/clienteslist',
  path: '/clienteslist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clienteslist': typeof AdminClienteslistRoute
  '/admin/main': typeof AdminMainRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/pedidoslist': typeof AdminPedidoslistRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/produtoslist': typeof AdminProdutoslistRoute
  '/admin/titulos': typeof AdminTitulosRoute
  '/admin/tituloslist': typeof AdminTituloslistRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/admin/vendedoreslist': typeof AdminVendedoreslistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clienteslist': typeof AdminClienteslistRoute
  '/admin/main': typeof AdminMainRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/pedidoslist': typeof AdminPedidoslistRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/produtoslist': typeof AdminProdutoslistRoute
  '/admin/titulos': typeof AdminTitulosRoute
  '/admin/tituloslist': typeof AdminTituloslistRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/admin/vendedoreslist': typeof AdminVendedoreslistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/clienteslist': typeof AdminClienteslistRoute
  '/admin/main': typeof AdminMainRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/pedidoslist': typeof AdminPedidoslistRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/produtoslist': typeof AdminProdutoslistRoute
  '/admin/titulos': typeof AdminTitulosRoute
  '/admin/tituloslist': typeof AdminTituloslistRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/admin/vendedoreslist': typeof AdminVendedoreslistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clienteslist'
    | '/admin/main'
    | '/admin/pedidos'
    | '/admin/pedidoslist'
    | '/admin/produtos'
    | '/admin/produtoslist'
    | '/admin/titulos'
    | '/admin/tituloslist'
    | '/admin/vendedores'
    | '/admin/vendedoreslist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clienteslist'
    | '/admin/main'
    | '/admin/pedidos'
    | '/admin/pedidoslist'
    | '/admin/produtos'
    | '/admin/produtoslist'
    | '/admin/titulos'
    | '/admin/tituloslist'
    | '/admin/vendedores'
    | '/admin/vendedoreslist'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/clientes'
    | '/admin/clienteslist'
    | '/admin/main'
    | '/admin/pedidos'
    | '/admin/pedidoslist'
    | '/admin/produtos'
    | '/admin/produtoslist'
    | '/admin/titulos'
    | '/admin/tituloslist'
    | '/admin/vendedores'
    | '/admin/vendedoreslist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendedoreslist': {
      id: '/admin/vendedoreslist'
      path: '/vendedoreslist'
      fullPath: '/admin/vendedoreslist'
      preLoaderRoute: typeof AdminVendedoreslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendedores': {
      id: '/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminVendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tituloslist': {
      id: '/admin/tituloslist'
      path: '/tituloslist'
      fullPath: '/admin/tituloslist'
      preLoaderRoute: typeof AdminTituloslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/titulos': {
      id: '/admin/titulos'
      path: '/titulos'
      fullPath: '/admin/titulos'
      preLoaderRoute: typeof AdminTitulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtoslist': {
      id: '/admin/produtoslist'
      path: '/produtoslist'
      fullPath: '/admin/produtoslist'
      preLoaderRoute: typeof AdminProdutoslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidoslist': {
      id: '/admin/pedidoslist'
      path: '/pedidoslist'
      fullPath: '/admin/pedidoslist'
      preLoaderRoute: typeof AdminPedidoslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/main': {
      id: '/admin/main'
      path: '/main'
      fullPath: '/admin/main'
      preLoaderRoute: typeof AdminMainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clienteslist': {
      id: '/admin/clienteslist'
      path: '/clienteslist'
      fullPath: '/admin/clienteslist'
      preLoaderRoute: typeof AdminClienteslistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminClienteslistRoute: typeof AdminClienteslistRoute
  AdminMainRoute: typeof AdminMainRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPedidoslistRoute: typeof AdminPedidoslistRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminProdutoslistRoute: typeof AdminProdutoslistRoute
  AdminTitulosRoute: typeof AdminTitulosRoute
  AdminTituloslistRoute: typeof AdminTituloslistRoute
  AdminVendedoresRoute: typeof AdminVendedoresRoute
  AdminVendedoreslistRoute: typeof AdminVendedoreslistRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminClienteslistRoute: AdminClienteslistRoute,
  AdminMainRoute: AdminMainRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPedidoslistRoute: AdminPedidoslistRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminProdutoslistRoute: AdminProdutoslistRoute,
  AdminTitulosRoute: AdminTitulosRoute,
  AdminTituloslistRoute: AdminTituloslistRoute,
  AdminVendedoresRoute: AdminVendedoresRoute,
  AdminVendedoreslistRoute: AdminVendedoreslistRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
